apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.myapplication.namespace }}
  labels:
    {{- include "myapplication.labels" . | nindent 4 }}
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  {{- if or (eq .Values.service.servicetype "LoadBalancer") ( eq .Values.service.servicetype "NodePort") }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.serviceport }}
    protocol: {{ .Values.service.serviceprotocal }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    {{- include "myapplication.labels" . | nindent 4 }}
    {{- toYaml .Values.labels | nindent 4 }}
  type: {{ .Values.service.servicetype }}